In [65]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv('dataset.csv')

In [67]:
df.head

<bound method NDFrame.head of         Name   Age  Gender  Admission Test Score  High School Percentage  \
0    Shehroz  24.0  Female                  50.0                   68.90
1      Waqar  21.0  Female                  99.0                   60.73
2     Bushra  17.0    Male                  89.0                     NaN
3      Aliya  17.0    Male                  55.0                   85.29
4      Bilal  20.0    Male                  65.0                   61.13
..       ...   ...     ...                   ...                     ...
152      Ali  19.0  Female                  85.0                   78.09
153    Bilal  17.0  Female                  81.0                   84.40
154   Fatima  21.0  Female                  98.0                   50.86
155   Shoaib  -1.0    Male                  91.0                   80.12
156     Maaz  17.0    Male                  88.0                   86.85

          City Admission Status
0       Quetta         Rejected
1      Karachi              NaN
2    Islamabad         Accepted
3      Karachi         Rejected
4       Lahore              NaN
..         ...              ...
152     Quetta         Accepted
153  Islamabad         Rejected
154     Multan         Accepted
155     Quetta         Accepted
156     Lahore         Accepted

[157 rows x 7 columns]>

In [68]:
df.shape

(157, 7)

In [69]:
df.columns

Index(['Name', 'Age', 'Gender', 'Admission Test Score',
       'High School Percentage', 'City', 'Admission Status'],
      dtype='object')

In [70]:
df.dtypes

Name                       object
Age                       float64
Gender                     object
Admission Test Score      float64
High School Percentage    float64
City                       object
Admission Status           object
dtype: object

In [71]:
df.isnull().sum()

Name                      10
Age                       10
Gender                    10
Admission Test Score      11
High School Percentage    11
City                      10
Admission Status          10
dtype: int64

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    147 non-null    object
 1   Age                     147 non-null    float64
 2   Gender                  147 non-null    object
 3   Admission Test Score    146 non-null    float64
 4   High School Percentage  146 non-null    float64
 5   City                    147 non-null    object
 6   Admission Status        147 non-null    object
dtypes: float64(3), object(4)
memory usage: 8.7+ KB

In [73]:
df.isnull().sum()

Name                      10
Age                       10
Gender                    10
Admission Test Score      11
High School Percentage    11
City                      10
Admission Status          10
dtype: int64

In [74]:
df.isnull().mean() * 100

Name                      6.369427
Age                       6.369427
Gender                    6.369427
Admission Test Score      7.006369
High School Percentage    7.006369
City                      6.369427
Admission Status          6.369427
dtype: float64

In [75]:
(df['Age'] < 0).sum()

,Name,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
23,Aliya,-1.0,Male,101.0,54.59,NaN,NaN
50,Shehroz,-1.0,Female,61.0,69.48,Quetta,Rejected
89,NaN,-1.0,Male,66.0,79.07,Rawalpindi,Rejected
113,Zunaira,-1.0,Female,84.0,58.77,Quetta,Rejected
155,Shoaib,-1.0,Male,91.0,80.12,Quetta,Accepted

In [76]:
df.loc[(df['Age'] < 0) | (df['Age'] > 40), 'Age'] = np.nan
df.loc[(df['Admission Test Score'] < 0) | (df['Admission Test Score'] > 100), 'Admission Test Score'] = np.nan
df.loc[(df['High School Percentage'] < 0) | (df['High School Percentage'] > 100), 'High School Percentage'] = np.nan

In [77]:
df.isnull().sum()

Name                      10
Age                       15
Gender                    10
Admission Test Score      14
High School Percentage    13
City                      10
Admission Status          10
dtype: int64

In [78]:
df = df.drop('Name', axis=1)

In [79]:
null_val = df.isna().sum()
data_types = df.dtypes

summary = pd.DataFrame({
    'Null values' : null_val,
    'data types' : data_types
    
})
summary

                        Null values data types
Age                              15    float64
Gender                           10     object
Admission Test Score             14    float64
High School Percentage           13    float64
City                             10     object
Admission Status                 10     object

In [80]:
age_mean = df['Age'].mean()
age_median = df['Age'].median()
print(age_mean)
print(age_median)

20.408450704225352
20.0

In [81]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Admission Test Score'] = df['Admission Test Score'].fillna(df['Admission Test Score'].median())
df['High School Percentage'] = df['High School Percentage'].fillna(df['High School Percentage'].median())
df['City'] = df['City'].fillna(df['City'].mode()[0])
df['Admission Status'] = df['Admission Status'].fillna(df['Admission Status'].mode()[0])

In [82]:
print(df['Gender'].unique())
print(df['City'].unique())
print(df['Admission Status'].unique())

['Female' 'Male']
['Quetta' 'Karachi' 'Islamabad' 'Lahore' 'Multan' 'Peshawar' 'Rawalpindi']
['Rejected' 'Accepted']

In [83]:
null_val = df.isna().sum()
data_types = df.dtypes
summary = pd.DataFrame({
    'Null values' : null_val,
    'data types' : data_types
    
})
summary

                        Null values data types
Age                               0    float64
Gender                            0     object
Admission Test Score              0    float64
High School Percentage            0    float64
City                              0     object
Admission Status                  0     object

In [84]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# df['Gender'] = le.fit_transform(df['Gender'])
# df['Admission Status'] = le.fit_transform(df['Admission Status'])

# summary2 = pd.DataFrame({
#     'Gender' : df['Gender'],
#     'Admission Status' : df['Admission Status']
# })
# summary2

df['Gender'] = df['Gender'].map({
    'Female' : 0,
    'Male' : 1
})
df['Admission Status'] = df['Admission Status'].map({
    'Rejected' : 0,
    'Accepted' : 1
})

summary2 = pd.DataFrame({
    'Gender' : df['Gender'],
    'Admission Status' : df['Admission Status']
})
summary2

     Gender  Admission Status
0         0                 0
1         0                 0
2         1                 1
3         1                 0
4         1                 0
..      ...               ...
152       0                 1
153       0                 0
154       0                 1
155       1                 1
156       1                 1

[157 rows x 2 columns]